version: '3'
services:
  master:
    image: ros:melodic-ros-core
    container_name: master
    command:
      - roscore

  bridge:
    image: fukurin/ros2:galactic-bridge
    container_name: bridge
    environment:
      - "ROS_HOSTNAME=bridge"
      - "ROS_MASTER_URI=http://master:11311"
    tty: true

  melodic:
    image: fukurin/ros:melodic-base
    container_name: melodic
    env_file: melodic.env
    volumes:
      # - /etc/passwd:/etc/passwd:ro
      # - /etc/group:/etc/group:ro
      - /dev/input:/dev/input
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $HOME/.Xauthority:$HOME/.Xauthority:rw
      - $HOME/ros_docker_ws/:$HOME:rw 
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
    tty: true

  galactic:
    image: fukurin/ros2:galactic-base
    container_name: galactic
    user: "${UID}:${GID}"
    volumes:
      - /dev/input:/dev/input
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $HOME/.Xauthority:$HOME/.Xauthority:rw
      - $HOME/ros2_ws/:/home/developer:rw
    environment: 
      - "XAUTHORITY=$HOME/.Xauthority"
      - "DISPLAY=${DISPLAY}"
      - "USER_ID=$UID"
      - "GROUP_ID=$GID"
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
    tty: true